import { WishlistItem } from '@/types/wishlist';

export const MOCK_WISHLIST: WishlistItem[] = [
  {
    id: 'wish-1',
    productId: 'prod-101',
    name: 'Sony WH-1000XM5 Noise Cancelling Headphones',
    price: 89900,
    originalPrice: 99900,
    image: 'https://via.placeholder.com/200?text=Headphones',
    seller: 'TechStore Myanmar',
    stock: 15,
    inStock: true,
    addedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'wish-2',
    productId: 'prod-102',
    name: 'Samsung Galaxy S24 Ultra Case - Clear',
    price: 15900,
    image: 'https://via.placeholder.com/200?text=Phone+Case',
    seller: 'AccessoriesHub',
    stock: 50,
    inStock: true,
    addedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'wish-3',
    productId: 'prod-103',
    name: 'Logitech MX Master 3S Wireless Mouse',
    price: 125000,
    originalPrice: 135000,
    image: 'https://via.placeholder.com/200?text=Mouse',
    seller: 'TechStore Myanmar',
    stock: 0,
    inStock: false,
    addedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'wish-4',
    productId: 'prod-104',
    name: 'Anker PowerCore 20000mAh Power Bank',
    price: 45000,
    image: 'https://via.placeholder.com/200?text=PowerBank',
    seller: 'GadgetWorld',
    stock: 23,
    inStock: true,
    addedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
