import type {
  AdminProfile,
  PlatformMetrics,
  AdminUser,
  AdminProduct,
  AdminBanner,
  AdminCoupon,
  AdminReportData,
} from "@/types/admin";

export const mockAdminProfile: AdminProfile = {
  id: "admin-001",
  name: "Khin Maung",
  email: "admin@crossmart.mm",
  avatar: "/avatars/admin-001.jpg",
  role: "super_admin",
  lastLogin: "2026-07-13T08:30:00Z",
};

export const mockPlatformMetrics: PlatformMetrics = {
  totalUsers: 12450,
  totalOrders: 8730,
  totalRevenue: 487500000,
  totalProducts: 3280,
  currency: "MMK",
  monthlyGrowth: 14.2,
  pendingApprovals: 23,
  activeSellers: 456,
};

export const mockAdminUsers: AdminUser[] = [
  {
    id: "user-001",
    name: "Aung Kyaw",
    email: "aungkyaw@gmail.com",
    role: "seller",
    status: "active",
    avatar: "/avatars/user-001.jpg",
    joinedDate: "2025-06-15",
    lastActive: "2026-07-12T14:22:00Z",
    totalOrders: 156,
    totalSpent: 0,
    currency: "MMK",
  },
  {
    id: "user-002",
    name: "May Thida",
    email: "maythida@gmail.com",
    role: "client",
    status: "active",
    avatar: "/avatars/user-002.jpg",
    joinedDate: "2025-08-20",
    lastActive: "2026-07-13T06:45:00Z",
    totalOrders: 23,
    totalSpent: 450000,
    currency: "MMK",
  },
  {
    id: "user-003",
    name: "Zaw Lin",
    email: "zawlin@crossmart.mm",
    role: "admin",
    status: "active",
    avatar: "/avatars/user-003.jpg",
    joinedDate: "2025-01-01",
    lastActive: "2026-07-13T09:00:00Z",
    totalOrders: 0,
    totalSpent: 0,
    currency: "MMK",
  },
  {
    id: "user-004",
    name: "Thin Zar",
    email: "thinzar@gmail.com",
    role: "client",
    status: "suspended",
    avatar: "/avatars/user-004.jpg",
    joinedDate: "2025-10-10",
    lastActive: "2026-05-01T11:30:00Z",
    totalOrders: 5,
    totalSpent: 75000,
    currency: "MMK",
  },
  {
    id: "user-005",
    name: "Nay Chi",
    email: "naychi@seller.mm",
    role: "seller",
    status: "pending",
    avatar: "/avatars/user-005.jpg",
    joinedDate: "2026-07-10",
    lastActive: "2026-07-10T16:00:00Z",
    totalOrders: 0,
    totalSpent: 0,
    currency: "MMK",
  },
  {
    id: "user-006",
    name: "Htet Aung",
    email: "htetaung@gmail.com",
    role: "client",
    status: "active",
    avatar: "/avatars/user-006.jpg",
    joinedDate: "2025-12-01",
    lastActive: "2026-07-11T20:15:00Z",
    totalOrders: 8,
    totalSpent: 132000,
    currency: "MMK",
  },
];

export const mockPendingProducts: AdminProduct[] = [
  {
    id: "prod-101",
    name: "Thai Herbal Soap Set - 6 Pieces",
    sellerName: "Bangkok Natural Shop",
    category: "Health & Beauty",
    price: 12000,
    currency: "MMK",
    status: "pending",
    image: "/products/herbal-soap.jpg",
    submittedAt: "2026-07-11T10:00:00Z",
    description:
      "Natural herbal soap set handmade in Thailand. Includes lemongrass, coconut, and aloe vera variants.",
  },
  {
    id: "prod-102",
    name: "Japanese Anime Keychain Collection",
    sellerName: "Otaku Corner",
    category: "Accessories",
    price: 5500,
    currency: "MMK",
    status: "pending",
    image: "/products/anime-keychain.jpg",
    submittedAt: "2026-07-12T14:30:00Z",
    description:
      "Limited edition anime keychain set. 10 different characters from popular series.",
  },
  {
    id: "prod-103",
    name: "Burmese Lacquerware Bowl Set",
    sellerName: "Bagan Artisans",
    category: "Home & Living",
    price: 45000,
    currency: "MMK",
    status: "pending",
    image: "/products/lacquerware.jpg",
    submittedAt: "2026-07-13T07:15:00Z",
    description:
      "Handcrafted lacquerware bowls from Bagan. Set of 4 bowls with intricate traditional patterns.",
  },
  {
    id: "prod-104",
    name: "Thai Silk Scarf - Premium Collection",
    sellerName: "Silk Paradise",
    category: "Fashion",
    price: 35000,
    currency: "MMK",
    status: "pending",
    image: "/products/silk-scarf.jpg",
    submittedAt: "2026-07-12T09:00:00Z",
    description:
      "Authentic Thai silk scarf with hand-woven patterns. Available in 5 colors. 100% pure silk.",
  },
  {
    id: "prod-105",
    name: "Bluetooth Wireless Earbuds Pro",
    sellerName: "TechZone Myanmar",
    category: "Electronics",
    price: 28000,
    currency: "MMK",
    status: "pending",
    image: "/products/earbuds.jpg",
    submittedAt: "2026-07-13T06:00:00Z",
    description:
      "True wireless earbuds with active noise cancellation, 30-hour battery life, and IPX5 water resistance.",
  },
  {
    id: "prod-106",
    name: "Shan Noodle Soup Kit - 4 Pack",
    sellerName: "Myanmar Delights",
    category: "Food & Beverages",
    price: 8500,
    currency: "MMK",
    status: "pending",
    image: "/products/shan-noodle.jpg",
    submittedAt: "2026-07-11T15:00:00Z",
    description:
      "Authentic Shan-style noodle soup kit. Just add hot water. Includes rice noodles, seasoning, and dried herbs.",
  },
  {
    id: "prod-107",
    name: "Rose Gold Minimalist Watch",
    sellerName: "Timepiece Studio",
    category: "Accessories",
    price: 65000,
    currency: "MMK",
    status: "approved",
    image: "/products/rose-watch.jpg",
    submittedAt: "2026-07-08T11:00:00Z",
    description:
      "Elegant rose gold watch with Japanese quartz movement and genuine leather strap. Water resistant 3ATM.",
  },
  {
    id: "prod-108",
    name: "Organic Green Tea - 100g Premium",
    sellerName: "Shan Tea House",
    category: "Food & Beverages",
    price: 15000,
    currency: "MMK",
    status: "approved",
    image: "/products/green-tea.jpg",
    submittedAt: "2026-07-05T08:00:00Z",
    description:
      "Hand-picked organic green tea from Shan State highlands. Rich in antioxidants with a smooth, earthy flavor.",
  },
  {
    id: "prod-109",
    name: "Bamboo Phone Stand - Handcrafted",
    sellerName: "Eco Craft Myanmar",
    category: "Home & Living",
    price: 4500,
    currency: "MMK",
    status: "approved",
    image: "/products/bamboo-stand.jpg",
    submittedAt: "2026-07-06T14:00:00Z",
    description:
      "Sustainable bamboo phone stand, hand-carved by local artisans. Adjustable angle, fits all phone sizes.",
  },
  {
    id: "prod-110",
    name: "Counterfeit Branded Handbag",
    sellerName: "Luxury Deals",
    category: "Fashion",
    price: 25000,
    currency: "MMK",
    status: "rejected",
    image: "/products/fake-bag.jpg",
    submittedAt: "2026-07-09T12:00:00Z",
    description:
      "High quality designer inspired handbag. Genuine leather. Multiple compartments.",
  },
  {
    id: "prod-111",
    name: "Unlicensed Energy Drink - 24 Pack",
    sellerName: "Quick Drinks Co",
    category: "Food & Beverages",
    price: 18000,
    currency: "MMK",
    status: "rejected",
    image: "/products/energy-drink.jpg",
    submittedAt: "2026-07-07T16:00:00Z",
    description:
      "High energy drink for active lifestyle. 250ml cans, pack of 24. Imported from China.",
  },
];

export const mockBanners: AdminBanner[] = [
  {
    id: "banner-001",
    title: "CrossMart Mega Sale",
    subtitle: "Up to 50% off on all cargo items",
    imageUrl: "/banners/mega-sale.jpg",
    href: "/products?promo=mega-sale",
    status: "active",
    position: "hero",
    startDate: "2026-07-01",
    endDate: "2026-07-31",
  },
  {
    id: "banner-002",
    title: "Free Shipping Week",
    subtitle: "Free delivery on orders over 100,000 MMK",
    imageUrl: "/banners/free-shipping.jpg",
    href: "/products",
    status: "active",
    position: "promo",
    startDate: "2026-07-10",
    endDate: "2026-07-17",
  },
  {
    id: "banner-003",
    title: "New Arrivals from Bangkok",
    subtitle: "Fresh stock every week from Thailand",
    imageUrl: "/banners/bangkok-arrivals.jpg",
    href: "/products?origin=thailand",
    status: "scheduled",
    position: "hero",
    startDate: "2026-07-20",
    endDate: "2026-08-20",
  },
  {
    id: "banner-004",
    title: "Refer & Earn",
    subtitle: "Get 10,000 MMK for every friend you invite",
    imageUrl: "/banners/refer-earn.jpg",
    href: "/referral",
    status: "inactive",
    position: "sidebar",
    startDate: "2026-06-01",
    endDate: "2026-06-30",
  },
];

export const mockCoupons: AdminCoupon[] = [
  {
    id: "coupon-001",
    code: "WELCOME10",
    type: "percentage",
    value: 10,
    minOrderAmount: 50000,
    maxDiscountAmount: 10000,
    maxUses: 1000,
    usedCount: 432,
    status: "active",
    validFrom: "2026-01-01",
    expiresAt: "2026-12-31",
    createdAt: "2026-01-01",
  },
  {
    id: "coupon-002",
    code: "SUMMER25",
    type: "percentage",
    value: 25,
    minOrderAmount: 100000,
    maxDiscountAmount: 25000,
    maxUses: 200,
    usedCount: 200,
    status: "expired",
    validFrom: "2026-06-01",
    expiresAt: "2026-07-01",
    createdAt: "2026-06-01",
  },
  {
    id: "coupon-003",
    code: "FLAT5000",
    type: "fixed",
    value: 5000,
    minOrderAmount: 30000,
    maxUses: 500,
    usedCount: 178,
    status: "active",
    validFrom: "2026-07-01",
    expiresAt: "2026-09-30",
    createdAt: "2026-07-01",
  },
  {
    id: "coupon-004",
    code: "SELLER20",
    type: "percentage",
    value: 20,
    minOrderAmount: 0,
    maxUses: 50,
    usedCount: 12,
    status: "active",
    validFrom: "2026-07-10",
    expiresAt: "2026-08-15",
    createdAt: "2026-07-10",
  },
];

// ---------------------------------------------------------------------------
// Reports & Analytics Mock Data
// ---------------------------------------------------------------------------

export const mockReportData: AdminReportData = {
  overview: {
    totalRevenue: 487500000,
    totalOrders: 8730,
    averageOrderValue: 55842,
    conversionRate: 3.8,
    revenueChange: 14.2,
    ordersChange: 11.5,
    aovChange: 2.4,
    conversionChange: 0.6,
  },
  salesOverTime: [
    { label: "Jan", revenue: 32000000, orders: 580 },
    { label: "Feb", revenue: 35000000, orders: 620 },
    { label: "Mar", revenue: 38000000, orders: 680 },
    { label: "Apr", revenue: 42000000, orders: 750 },
    { label: "May", revenue: 40000000, orders: 710 },
    { label: "Jun", revenue: 45000000, orders: 800 },
    { label: "Jul", revenue: 48000000, orders: 850 },
    { label: "Aug", revenue: 52000000, orders: 920 },
    { label: "Sep", revenue: 47000000, orders: 830 },
    { label: "Oct", revenue: 55000000, orders: 980 },
    { label: "Nov", revenue: 58000000, orders: 1020 },
    { label: "Dec", revenue: 60000000, orders: 1050 },
  ],
  ordersByMonth: [
    { label: "Jan", revenue: 0, orders: 580 },
    { label: "Feb", revenue: 0, orders: 620 },
    { label: "Mar", revenue: 0, orders: 680 },
    { label: "Apr", revenue: 0, orders: 750 },
    { label: "May", revenue: 0, orders: 710 },
    { label: "Jun", revenue: 0, orders: 800 },
    { label: "Jul", revenue: 0, orders: 850 },
    { label: "Aug", revenue: 0, orders: 920 },
    { label: "Sep", revenue: 0, orders: 830 },
    { label: "Oct", revenue: 0, orders: 980 },
    { label: "Nov", revenue: 0, orders: 1020 },
    { label: "Dec", revenue: 0, orders: 1050 },
  ],
  revenueByCategory: [
    { category: "Electronics", revenue: 145000000, percentage: 29.7 },
    { category: "Fashion", revenue: 110000000, percentage: 22.6 },
    { category: "Home & Living", revenue: 85000000, percentage: 17.4 },
    { category: "Health & Beauty", revenue: 65000000, percentage: 13.3 },
    { category: "Food & Beverages", revenue: 50000000, percentage: 10.3 },
    { category: "Accessories", revenue: 32500000, percentage: 6.7 },
  ],
  topSellers: [
    { seller: "TechZone Myanmar", revenue: 85000000, orders: 1520 },
    { seller: "Bangkok Natural Shop", revenue: 62000000, orders: 1100 },
    { seller: "Silk Paradise", revenue: 48000000, orders: 850 },
    { seller: "Myanmar Delights", revenue: 35000000, orders: 780 },
    { seller: "Shan Tea House", revenue: 28000000, orders: 620 },
  ],
  newUsersOverTime: [
    { label: "Jan", count: 850 },
    { label: "Feb", count: 920 },
    { label: "Mar", count: 1100 },
    { label: "Apr", count: 980 },
    { label: "May", count: 1250 },
    { label: "Jun", count: 1400 },
    { label: "Jul", count: 1550 },
    { label: "Aug", count: 1300 },
    { label: "Sep", count: 1150 },
    { label: "Oct", count: 1450 },
    { label: "Nov", count: 1600 },
    { label: "Dec", count: 1700 },
  ],
  usersByRole: [
    { role: "Client", count: 11200 },
    { role: "Seller", count: 456 },
    { role: "Admin", count: 12 },
  ],
  activeUsers: {
    daily: 2850,
    weekly: 8900,
    monthly: 12450,
  },
};
